# Generated by Django 3.2.13 on 2022-12-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_ni', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('14', '14')], max_length=4000, null=True, verbose_name='Номера отделов')),
                ('numberInput', models.IntegerField(blank=True, null=True, verbose_name='Номер исходящий')),
                ('res_nm', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Номер исходящий и дата')),
                ('adresat', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Адресат (кому направлен)')),
                ('content', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Краткое содержание')),
                ('executor', models.CharField(blank=True, max_length=4000, null=True, verbose_name='исполнитель')),
                ('note', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Примечание')),
            ],
        ),
    ]
